# Generated by Django 2.1.7 on 2020-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20201125_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='pitch',
            field=models.TextField(blank=True),
        ),
    ]
