# Generated by Django 2.1.7 on 2020-11-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_bid_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor_profile',
            field=models.TextField(blank=True),
        ),
    ]
