# Generated by Django 2.1.7 on 2020-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20201204_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag_line',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
