# Generated by Django 2.1.7 on 2020-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20201204_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tutor_profile',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
