# Generated by Django 2.1.7 on 2020-11-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20201128_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
