# Generated by Django 2.1.7 on 2020-12-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20201204_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tag_line',
            new_name='tagline',
        ),
    ]
