# Generated by Django 2.1.7 on 2020-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20201128_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medium_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_channel',
            field=models.URLField(blank=True),
        ),
    ]
