# Generated by Django 2.1.7 on 2020-11-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20201128_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialtylist',
        ),
        migrations.AddField(
            model_name='user',
            name='specialtylist',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='marketplace.Category'),
        ),
    ]
